previousNext()
        self.driver.find_element_by_xpath("xpath=//*[@id='price']").send_keys('55')
        self.driver.find_element_by_xpath("xpath=//*[@id='volume']").send_keys('66')
        self.driver.find_element_by_xpath("xpath=//*[@id='odometer']").send_keys('72')
        self.driver.find_element_by_xpath("xpath=//*[@text='Save Fillup']").click()
        self.driver.find_element_by_xpath("xpath=//*[@id='price']").send_keys('26')
        self.driver.find_element_by_xpath("xpath=//*[@id='volume']").send_keys('55')
        self.driver.find_element_by_xpath("xpath=//*[@id='odometer']").send_keys('29')
        self.driver.find_element_by_xpath("xpath=//*[@text='Save Fillup']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='History']").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@id='icon' and (./preceding-sibling::* | ./following-sibling::*)[@text='Fillup']]')))
        self.driver.find_element_by_xpath("xpath=//*[@id='icon' and (./preceding-sibling::* | ./following-sibling::*)[@text='Fillup']]").send_keys('22')
        self.driver.find_element_by_xpath("xpath=//*[@id='volume']").send_keys('22')
        self.driver.find_element_by_xpath("xpath=//*[@id='odometer']").send_keys('22')
        self.driver.find_element_by_xpath("xpath=//*[@text='12/12/20']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='OK']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='Save Fillup']").click()
        self.driver.find_element_by_xpath("xpath=//*[@id='icon' and (./preceding-sibling::* | ./following-sibling::*)[@text='Fillup']]").click()
        self.driver.find_element_by_xpath("xpath=//*[@id='price']").send_keys('33')
        self.driver.find_element_by_xpath("xpath=//*[@id='volume']").send_keys('33')
        self.driver.find_element_by_xpath("xpath=//*[@id='odometer']").send_keys('33')
        self.driver.find_element_by_xpath("xpath=//*[@text='12/12/20']").click()
        self.driver.find_element_by_xpath("xpath=//*[@contentDescription='Increase day']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='OK']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='Save Fillup']").click()
        self.driver.find_element_by_xpath("xpath=//*[@id='icon' and (./preceding-sibling::* | ./following-sibling::*)[@text='Fillup']]").click()
        self.driver.find_element_by_xpath("xpath=//*[@id='price']").send_keys('77')
        self.driver.find_element_by_xpath("xpath=//*[@id='volume']").click()
        self.driver.find_element_by_xpath("xpath=//*[@id='volume']").send_keys('77')
        self.driver.find_element_by_xpath("xpath=//*[@id='odometer']").click()
        self.driver.find_element_by_xpath("xpath=//*[@id='odometer']").send_keys('77')
        self.driver.find_element_by_xpath("xpath=//*[@text='12/12/20']").click()
        self.driver.find_element_by_xpath("xpath=//*[@contentDescription='Decrease day']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='OK']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='Save Fillup']").click()
        self.driver.find_element_by_xpath("xpath=//*[@id='icon' and (./preceding-sibling::* | ./following-sibling::*)[@text='History']]").click()
        WebDriverWait(self.driver, 60).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@class='android.widget.LinearLayout' and ./*[@text='12/11/20']]')))
        self.driver.find_element_by_xpath("xpath=//*[@class='android.widget.LinearLayout' and ./*[@text='12/11/20']]").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Previous']')))
        self.driver.find_element_by_xpath("xpath=//*[@text='Previous']").click()
        WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@text='Next']')))
        self.driver.find_element_by_xpath("xpath=//*[@text='Next']").click()

        -------------------------------

        validaOrden()

        self.driver.find_element_by_xpath("xpath=//*[@id='price']").send_keys('55')
        self.driver.find_element_by_xpath("xpath=//*[@id='volume']").send_keys('66')
        self.driver.find_element_by_xpath("xpath=//*[@id='odometer']").send_keys('72')
        self.driver.find_element_by_xpath("xpath=//*[@text='Save Fillup']").click()
        self.driver.find_element_by_xpath("xpath=//*[@id='price']").send_keys('26')
        self.driver.find_element_by_xpath("xpath=//*[@id='volume']").send_keys('55')
        self.driver.find_element_by_xpath("xpath=//*[@id='odometer']").send_keys('29')
        self.driver.find_element_by_xpath("xpath=//*[@text='Save Fillup']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='History']").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@id='icon' and (./preceding-sibling::* | ./following-sibling::*)[@text='Fillup']]')))
        self.driver.find_element_by_xpath("xpath=//*[@id='icon' and (./preceding-sibling::* | ./following-sibling::*)[@text='Fillup']]").send_keys('22')
        self.driver.find_element_by_xpath("xpath=//*[@id='volume']").send_keys('22')
        self.driver.find_element_by_xpath("xpath=//*[@id='odometer']").send_keys('22')
        self.driver.find_element_by_xpath("xpath=//*[@text='12/12/20']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='OK']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='Save Fillup']").click()
        self.driver.find_element_by_xpath("xpath=//*[@id='icon' and (./preceding-sibling::* | ./following-sibling::*)[@text='Fillup']]").click()
        self.driver.find_element_by_xpath("xpath=//*[@id='price']").send_keys('33')
        self.driver.find_element_by_xpath("xpath=//*[@id='volume']").send_keys('33')
        self.driver.find_element_by_xpath("xpath=//*[@id='odometer']").send_keys('33')
        self.driver.find_element_by_xpath("xpath=//*[@text='12/12/20']").click()
        self.driver.find_element_by_xpath("xpath=//*[@contentDescription='Increase day']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='OK']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='Save Fillup']").click()
        self.driver.find_element_by_xpath("xpath=//*[@id='icon' and (./preceding-sibling::* | ./following-sibling::*)[@text='Fillup']]").click()
        self.driver.find_element_by_xpath("xpath=//*[@id='price']").send_keys('77')
        self.driver.find_element_by_xpath("xpath=//*[@id='volume']").click()
        self.driver.find_element_by_xpath("xpath=//*[@id='volume']").send_keys('77')
        self.driver.find_element_by_xpath("xpath=//*[@id='odometer']").click()
        self.driver.find_element_by_xpath("xpath=//*[@id='odometer']").send_keys('77')
        self.driver.find_element_by_xpath("xpath=//*[@text='12/12/20']").click()
        self.driver.find_element_by_xpath("xpath=//*[@contentDescription='Decrease day']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='OK']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='Save Fillup']").click()
        self.driver.find_element_by_xpath("xpath=//*[@id='icon' and (./preceding-sibling::* | ./following-sibling::*)[@text='History']]").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='12/11/20']").click()
        self.driver.press_keycode(4) # back
        self.driver.find_element_by_xpath("xpath=//*[@text='12/12/20']").click()
        self.driver.press_keycode(4) # back
        self.driver.find_element_by_xpath("xpath=//*[@text='12/13/20']").click()
        self.driver.press_keycode(4) # back
        ------------------------------------------

           validaStats()

            self.driver.find_element_by_xpath("xpath=//*[@id='price']").send_keys('55')
        self.driver.find_element_by_xpath("xpath=//*[@id='volume']").send_keys('66')
        self.driver.find_element_by_xpath("xpath=//*[@id='odometer']").send_keys('72')
        self.driver.find_element_by_xpath("xpath=//*[@text='Save Fillup']").click()
        self.driver.find_element_by_xpath("xpath=//*[@id='price']").send_keys('26')
        self.driver.find_element_by_xpath("xpath=//*[@id='volume']").send_keys('55')
        self.driver.find_element_by_xpath("xpath=//*[@id='odometer']").send_keys('29')
        self.driver.find_element_by_xpath("xpath=//*[@text='Save Fillup']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='History']").click()
        WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@id='icon' and (./preceding-sibling::* | ./following-sibling::*)[@text='Fillup']]')))
        self.driver.find_element_by_xpath("xpath=//*[@id='icon' and (./preceding-sibling::* | ./following-sibling::*)[@text='Fillup']]").send_keys('22')
        self.driver.find_element_by_xpath("xpath=//*[@id='volume']").send_keys('22')
        self.driver.find_element_by_xpath("xpath=//*[@id='odometer']").send_keys('22')
        self.driver.find_element_by_xpath("xpath=//*[@text='12/12/20']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='OK']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='Save Fillup']").click()
        self.driver.find_element_by_xpath("xpath=//*[@id='icon' and (./preceding-sibling::* | ./following-sibling::*)[@text='Fillup']]").click()
        self.driver.find_element_by_xpath("xpath=//*[@id='price']").send_keys('33')
        self.driver.find_element_by_xpath("xpath=//*[@id='volume']").send_keys('33')
        self.driver.find_element_by_xpath("xpath=//*[@id='odometer']").send_keys('33')
        self.driver.find_element_by_xpath("xpath=//*[@text='12/12/20']").click()
        self.driver.find_element_by_xpath("xpath=//*[@contentDescription='Increase day']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='OK']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='Save Fillup']").click()
        self.driver.find_element_by_xpath("xpath=//*[@id='icon' and (./preceding-sibling::* | ./following-sibling::*)[@text='Fillup']]").click()
        self.driver.find_element_by_xpath("xpath=//*[@id='price']").send_keys('77')
        self.driver.find_element_by_xpath("xpath=//*[@id='volume']").click()
        self.driver.find_element_by_xpath("xpath=//*[@id='volume']").send_keys('77')
        self.driver.find_element_by_xpath("xpath=//*[@id='odometer']").click()
        self.driver.find_element_by_xpath("xpath=//*[@id='odometer']").send_keys('77')
        self.driver.find_element_by_xpath("xpath=//*[@text='12/12/20']").click()
        self.driver.find_element_by_xpath("xpath=//*[@contentDescription='Decrease day']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='OK']").click()
        self.driver.find_element_by_xpath("xpath=//*[@text='Save Fillup']").click()
        WebDriverWait(self.driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH,'//*[@id='icon' and (./preceding-sibling::* | ./following-sibling::*)[@text='Statistics']]')))
        WebElement result1= (self.driver.find_element_by_xpath("xpath=//*[@text='$484.00']"))
        WebElement result2= (self.driver.find_element_by_xpath("xpath=//*[@text='$2500.67']"))
        WebElement result3= (self.driver.find_element_by_xpath("xpath=//*[@text='$5929.00']"))
        Assert.assertEquals(result1.getText(), "$484.00");
        Assert.assertEquals(result2.getText(), "$2500.67");
        Assert.assertEquals(result3.getText(), "$5929.00");
